### ISSUE TITLE
Is the implementation of LBL-NCE complete?

### ISSUE THREAD

**Issue by rahul003** [ddahlmeier/neural_lm#1]
Hello,

First of all, I know an issue is a bad place to message. Sorry, but I had no way of reaching you other than this. I will delete the issue once you reply.

I am a beginner learning about these topics by referring to your code along with the paper. Can you please let me know if your implementation of LBL-NCE is complete?

**Comment by ddahlmeier** [comment]
Hello Rahul,

no, the NCE code is not working yet. I am trying to figure out how to  
implement  NCE with Theano myself.

The maximum likelihood learning in lbl.py is already working.

regards,
Daniel

**Comment by rahul003** [comment]
Ok, thanks!

**Comment by yinwenpeng** [comment]
hello, ddahlmeier,

I have the same question: could the LBL-NCE work now?  Thanks!!!

**Comment by ddahlmeier** [comment]
No, I haven't had time to work on the NCE implementation. I hope to get back to it soon. If anyone would like to contribute, you are more than welcome.
